function confidence_intervals = QTcalculate_ci_from_jacobian(jacobian, params, residuals, resnorm, alpha)
% This script calculates confidence intervals of fit parameters from the
% Jacobian generated by lsqcurvefit
% INPUTS:   jacobian    = Jacobian
%           params      = fit parameters
%           residuals   = residuals of the fit
%           resnorm     = sum of sqaured residuals
%           alpha       = significance level
% OUTPUT:   confidence_intervals    = confidence intervals on the fit
%                                     parameters

N = length(residuals);  % N = number of datapoints
p = length(params);     % p = number of parameters
dof = N - p;            % dof = degrees of freedom

sigma2 = resnorm / dof; % residual variance
cov_matrix = sigma2 * inv(jacobian' * jacobian);    % covariance matrix
SE = sqrt(diag(cov_matrix));    %   standard errors

t_val = tinv(1 - alpha/2, dof); % critical t value at significance level alpha

CI_lower = params' - t_val * SE; % confidence interval - lower
CI_upper = params' + t_val * SE; % confidence interval - upper

confidence_intervals = [CI_lower, CI_upper];

end
