function handles = QT_menuSetup(handles)
%Generates the menu bar for QuantiTrack after having difficulties with the
%Guide Menu editor
%File menu
 
handles.FileMenu = uimenu(handles.figure1,'Text','File');

handles.LoadMat = uimenu(handles.FileMenu,'Text','Load Mat-Track File',...
    'Accelerator','O',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('LoadMat_Callback',hObject,eventdata,guidata(hObject)));

handles.SaveToDatabase = uimenu(handles.FileMenu,'Text','Save to Track Database',...
    'Accelerator','S',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('SaveToDatabase_Callback',hObject,eventdata,guidata(hObject)));

handles.SaveMat = uimenu(handles.FileMenu,'Text','Save a copy of the Track results',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('SaveMat_Callback',hObject,eventdata,guidata(hObject)));

handles.ExportToWorkSpace = uimenu(handles.FileMenu,'Text','Export to WorkSpace',...
    'Accelerator','E',...
    'Separator','on',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('ExportToWorkSpace_Callback',hObject,eventdata,guidata(hObject)));

handles.ExportParamsMenu = uimenu(handles.FileMenu,'Text','Copy Tracking and Analysis Parameters',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('ExportParamsMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.LoadFiltImageMenu = uimenu(handles.FileMenu,'Text','Import Filtered Image',...
    'Separator','on',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('LoadFiltImageMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.SaveFilterMenu = uimenu(handles.FileMenu,'Text','Save Filtered Image',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('SaveFilterMenu_Callback',hObject,eventdata,guidata(hObject)));

% handles.ImportSOS = uimenu(handles.FileMenu,'Text','Import SOS Tracking Data',...
%     'Separator','on',...
%     'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('ImportSOS_Callback',hObject,eventdata,guidata(hObject)));

handles.uTrackImport = uimenu(handles.FileMenu,'Text','Import uTrack Tracking Data',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('uTrackImport_Callback',hObject,eventdata,guidata(hObject)));




%Parameters menu
handles.SetPar = uimenu(handles.figure1,'Text','Parameters');

handles.EditProfileMenu = uimenu(handles.SetPar,'Text','Edit Profile Parameters',...
    'Accelerator','P',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('EditProfileMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.SetAcqPar = uimenu(handles.SetPar,'Text','Set Acquisition Parameters',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('SetAcqPar_Callback',hObject,eventdata,guidata(hObject)));

handles.SetCheckPar = uimenu(handles.SetPar,'Text','Set Checking Parameters',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('SetCheckPar_Callback',hObject,eventdata,guidata(hObject)));

handles.SetAnPar = uimenu(handles.SetPar,'Text','Set Analysis Parameters',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('SetAnPar_Callback',hObject,eventdata,guidata(hObject)));

handles.SetBoundPar = uimenu(handles.SetPar,'Text','Set Bound Thresholds',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('SetBoundPar_Callback',hObject,eventdata,guidata(hObject)));

handles.LAP_setParamsMenu = uimenu(handles.SetPar,'Text','Set LAP tracking Parameters',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('LAP_setParamsMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.MTT_setParamsMenu = uimenu(handles.SetPar,'Text','Set MTT Tracking Parameters',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('MTT_setParamsMenu_Callback',hObject,eventdata,guidata(hObject)));

%Tools menu
handles.ToolMenu = uimenu(handles.figure1,'Text','Tools');

handles.ParallelUseSelect = uimenu(handles.ToolMenu,'Text','Use Parallel Computing',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('ParallelUseSelect_Callback',hObject,eventdata,guidata(hObject)));

handles.NminCalcMenu = uimenu(handles.ToolMenu,'Text','Nmin Calculator',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('NminCalcMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.SpltAlignMenu = uimenu(handles.ToolMenu,'Text','Split/Align Color Tool',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('SpltAlignMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.BatchRetrackMenu = uimenu(handles.ToolMenu,'Text','Batch Retrack mat files',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('BatchRetrackMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.fullBatchTrackingMenu = uimenu(handles.ToolMenu,'Text','Full Batch Processing',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('fullBatchTrackingMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.TrackTableGenMenu = uimenu(handles.ToolMenu,'Text','Compile Track Tables',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('TrackTableGenMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.TrackTableMerge = uimenu(handles.ToolMenu,'Text','Merge Track Tables',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('TrackTableMerge_Callback',hObject,eventdata,guidata(hObject)));

%Machine learning submenu
handles.MLsubMenu = uimenu(handles.ToolMenu,'Text','Machine Learning');

handles.SpotTrainMenu = uimenu(handles.MLsubMenu,'Text','AI Spot Training ',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('SpotTrainMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.filterPartButton = uimenu(handles.MLsubMenu,'Text','Filter Particles ',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('filterPartButton_Callback',hObject,eventdata,guidata(hObject)));
%end submenu

handles.PixelTcourse = uimenu(handles.ToolMenu,'Text','Measure Pixel Intensities over Time',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('PixelTcourse_Callback',hObject,eventdata,guidata(hObject)));

handles.Photobleach_merge = uimenu(handles.ToolMenu,'Text','Merge data and calculate bleaching rates',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('Photobleach_merge_Callback',hObject,eventdata,guidata(hObject)));

handles.BleachCompare = uimenu(handles.ToolMenu,'Text','Compare Bleaching of conditions',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('BleachCompare_Callback',hObject,eventdata,guidata(hObject)));

handles.ResBoxplots = uimenu(handles.ToolMenu,'Text','Compare Residence times of conditions',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('ResBoxplots_Callback',hObject,eventdata,guidata(hObject)));

handles.ROIsurvival_menu = uimenu(handles.ToolMenu,'Text','Merge data and calculate ROI survivals',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('ROIsurvival_menu_Callback',hObject,eventdata,guidata(hObject)));

handles.MovieFromTracking = uimenu(handles.ToolMenu,'Text','Batch Movies from Track Files',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('MovieFromTracking_Callback',hObject,eventdata,guidata(hObject)));

handles.Gmask_tracks = uimenu(handles.ToolMenu,'Text','Gaussian Mask Spots',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('Gmask_tracks_Callback',hObject,eventdata,guidata(hObject)));

handles.CalcBoundParamsMenu = uimenu(handles.ToolMenu,'Text','Calculate Bound Parameters from Stable Protein',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('CalcBoundParamsMenu_Callback',hObject,eventdata,guidata(hObject)));

%ROIs Menu
handles.ROImenu = uimenu(handles.figure1,'Text','ROIs');

handles.SetAutoROIparams = uimenu(handles.ROImenu,'Text','Set autoROI parameters',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('SetAutoROIparams_Callback',hObject,eventdata,guidata(hObject)));

handles.autoROImenu = uimenu(handles.ROImenu,'Text','Find small moving ROIs',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('autoROImenu_Callback',hObject,eventdata,guidata(hObject)));

handles.autoROIsLarge = uimenu(handles.ROImenu,'Text','Find large immobile ROIs',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('autoROIsLarge_Callback',hObject,eventdata,guidata(hObject)));

handles.ROITool_menu = uimenu(handles.ROImenu,'Text','ROI Tool',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('ROITool_menu_Callback',hObject,eventdata,guidata(hObject)));

handles.BatchTrack_menu = uimenu(handles.ROImenu,'Text','Batch Tracking (tif files, use ROI Tool first)',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('BatchTrack_menu_Callback',hObject,eventdata,guidata(hObject)));

handles.ImportMMorphROIs = uimenu(handles.ROImenu,'Text','Import ROIs from Metamorph',...
    'Separator','on',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('ImportMMorphROIs_Callback',hObject,eventdata,guidata(hObject)));

handles.ImportImageJROIs = uimenu(handles.ROImenu,'Text','Import ROIs from ImageJ',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('ImportImageJROIs_Callback',hObject,eventdata,guidata(hObject)));

handles.ROIareas2clip_menu = uimenu(handles.ROImenu,'Text','Copy ROI Areas to Clipboard',...
    'Separator','on',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('ROIareas2clip_menu_Callback',hObject,eventdata,guidata(hObject)));

%Tracking QC menu
handles.QCmenu = uimenu(handles.figure1,'Text','Tracking QC');

handles.TrackIntPlotMenu = uimenu(handles.QCmenu,'Text','Track Intensity Tool',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('TrackIntPlotMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.CheckTrackMenu = uimenu(handles.QCmenu,'Text','Manually Check Tracks',...
    'Separator','on',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('CheckTrackMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.TrackDim_menu = uimenu(handles.QCmenu,'Text','Check Tracks with Dimensions',...
    'Enable','off',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('TrackDim_menu_Callback',hObject,eventdata,guidata(hObject)));

handles.CheckSNR_batch = uimenu(handles.QCmenu,'Text','Merge and check SNR',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('CheckSNR_batch_Callback',hObject,eventdata,guidata(hObject)));

handles.TrackQC_batch = uimenu(handles.QCmenu,'Text','Merge and estimate tracking errors',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('TrackQC_batch_Callback',hObject,eventdata,guidata(hObject)));

%Further Analysis menu
handles.MoreAnalysis = uimenu(handles.figure1,'Text','Further Analysis');

handles.ResTimeMerge_Histone = uimenu(handles.MoreAnalysis,'Text','Merge data and analyze residence time distribution',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('ResTimeMerge_Histone_Callback',hObject,eventdata,guidata(hObject)));

handles.ResAnalOpenHist = uimenu(handles.MoreAnalysis,'Text','Open residence time analysis',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('ResAnalOpenHist_Callback',hObject,eventdata,guidata(hObject)));

handles.JDH_Merge = uimenu(handles.MoreAnalysis,'Text','Merge and analyze jump histograms',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('JDH_Merge_Callback',hObject,eventdata,guidata(hObject)));

handles.JDHanalOpen = uimenu(handles.MoreAnalysis,'Text','Open jump histogram analysis',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('JDH_Open_Callback',hObject,eventdata,guidata(hObject)));

handles.SpotOnRun = uimenu(handles.MoreAnalysis,'Text','Merge data and run Spot-On',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('SpotOnRun_Callback',hObject,eventdata,guidata(hObject)));

handles.DiffCoeffMerge = uimenu(handles.MoreAnalysis,'Text','Merge and analyze Diffusion Coefficients',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('DiffCoeffMerge_Callback',hObject,eventdata,guidata(hObject)));

handles.MSD_merge = uimenu(handles.MoreAnalysis,'Text','Merge and analyze MSD curve',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('MSD_merge_Callback',hObject,eventdata,guidata(hObject)));

handles.MergeAnglesMenu = uimenu(handles.MoreAnalysis,'Text','Merge and analyze angles',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('MergeAnglesMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.pEManalysisMenu = uimenu(handles.MoreAnalysis,'Text','Merge data and run pEM analysis',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('pEManalysisMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.RLanalysisMenu = uimenu(handles.MoreAnalysis,'Text','Merge data and run RL analysis',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('RLanalysisMenu_Callback',hObject,eventdata,guidata(hObject)));

handles.mergeTrackAreas = uimenu(handles.MoreAnalysis,'Text','Merge and analyze Track coverage areas',...
    'Separator','on',...
    'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('mergeTrackAreas_Callback',hObject,eventdata,guidata(hObject)));

% handles.Tracks_Col = uimenu(handles.MoreAnalysis,'Text','Colocalize Tracks - PolII',...
%     'Separator','on',...
%     'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('Tracks_Col_Callback',hObject,eventdata,guidata(hObject)));
% 
% handles.TwoColorSMC = uimenu(handles.MoreAnalysis,'Text','2 color SMT colocalization',...
%     'MenuSelectedFcn',@(hObject,eventdata)QuantiTrack('TwoColorSMC_Callback',hObject,eventdata,guidata(hObject)));

